language: python


python:
    - "2.6"
    - "2.7"
    - "3.2"
    - "3.3"

env:
    - DJANGO=1.4
    - DJANGO=1.5
    - DJANGO=1.6
    - DJANGO=1.7

install:
    - pip install -q Django==$DJANGO --use-mirrors
    - pip install -q . --use-mirrors
    - pip install -q -r requirements.txt --use-mirrors

before_script:
    - bash ./travis_postgis_setup.sh

script: python example/manage.py test conduit

matrix:
  exclude:
    - python: "3.2"
      env: DJANGO=1.4
    - python: "3.3"
      env: DJANGO=1.4
