language: python


python:
    - "2.6"
    - "2.7"
    - "3.2"
    - "3.3"

env:
    - DJANGO=1.6
    - DJANGO=1.7
    - DJANGO=1.8
    - DJANGO=1.9
    - DJANGO=1.10

install:
    - pip install -q Django==$DJANGO
    - pip install -q .
    - pip install -q -r requirements.txt

before_script:
    - bash ./travis_postgis_setup.sh

script: python example/manage.py test conduit

matrix:
  exclude:
    - python: "2.6"
      env: DJANGO=1.7
    - python: "2.6"
      env: DJANGO=1.8
    - python: "2.6"
      env: DJANGO=1.9
    - python: "2.6"
      env: DJANGO=1.10
