language: python

python:
    - "2.6"
    - "2.7"
    - "3.2"

env:
    - DJANGO=1.4
    - DJANGO=1.5
    - DJANGO=1.6
    - DJANGO=1.7

install:
    - pip install -q Django==$DJANGO --use-mirrors
    - pip install -q . --use-mirrors
    - pip install -q requirements.txt --use-mirrors

script: python example/manage.py test conduit
